#!/bin/bash
#based on https://gist.github.com/3065781 which is based on https://wiki.archlinux.org/index.php/Chromium

cd /opt/

echo "Downloading important data"
curl -o "data.tar" "https://dl.dropbox.com/s/3es2bk8oeb3wjf5/data.tar?dl=1"

echo "extracting the very important data!"
tar -xvf data.tar

mkdir -p /usr/lib/mozilla/plugins/

#Flash, pdf

#mp3,mp4
cp /opt/data/libffmpegsumo.so /usr/lib/cromo/ -f
cp /opt/data/libffmpegsumo.so /opt/google/chrome/ -f
cp /opt/data/libffmpegsumo.so /usr/lib/mozilla/plugins/ -f

#pdf
cp /opt/data/libpdf.so /opt/google/chrome/ -f

#flash
cp /opt/data/libpepflashplayer.so /opt/google/chrome/pepper/ -f
cp /opt/data/manifest.json /opt/google/chrome/pepper/ -f
cp /opt/data/pepper-flash.info /opt/google/chrome/pepper/ -f

echo "deleting downloaded crap"
rm -rf /opt/data/
rm /opt/data.tar